name = "BartIO"
uuid = "8b90e6a2-6e4d-4906-89ae-b5f72ca4a65b"
authors = ["Jakob Asslaender <jakob.asslaender@nyumc.org>", "Aur√©lien Trotier <a.trotier@gmail.com>"]
version = "0.2.0"

[deps]
BufferedStreams = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"
ConfParser = "88353bc9-fd38-507d-a820-d3b43837d6b9"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
